---
title: "Is there evidence of White Flight in Boston over the last 20 years?"
author: Rachel Kwon, Erin Mahoney, & Kevin Nazario
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: yeti
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard) # for the dashboard
library(shiny)
library(magrittr)
library(stringr)
library(RColorBrewer)
library(viridis)

#map libraries - need these to load shapefile
library(leaflet)
library(htmltools)
library(tigris)
library(sf)
load('SavedData.Rdata') # load data from same directory as RMD file

# color choice variables into vector
color_choices <- c("Viridis"= "viridis", "Magma"="magma", "Plasma"="plasma", "Inferno"="inferno", "Spectral"= "Spectral", "Red-Yellow-Blue"= "RdYlBu", "Blues"= "Blues", "Random"= "Set1")

#set city variables into vector
cities <- c('Boston, MA'='MA', 'D.C.' = 'DC', 'Oakland, CA'= 'CA', 'Seattle, WA' = 'WA', 'Portland, OR'= 'OR', 'Knoxville, TN'= 'TN', 'Detroit, MI' = 'MI') 

```

Maps{data-orientation=rows}
=====================================

Column {.sidebar} 
-----------------------------------------------------------------------

### Visualizing Change in White population over time

```{r}
#City Dropdown
selectInput("cities", "Choose a city:",
      choices = cities, 
      selected = cities[1])
#Year Dropdown
selectInput("year", "Choose a year:",
      c('1990', '2000', '2010'), 
      selected = '1990')
#Color Drop Down
selectInput("palette", "Choose a color palette:",
            choices = color_choices, selected = color_choices[1])

checkboxInput("reverse", label = "Reverse Colors?")
```

**Note: The map will update every time you change the city, year or color scheme. 

Hovering over the pay will show the percentage of white people in the current tract as well as the number of white people (i.e. 35% (200) means the tract is 35% white with 200 white people according to the decennial census). 

Clicking on an area of the map will tell you the name/number of the given tract. 

Row
-----------------------------------------------------------------------

### 
```{r} 
#Render map
(map1<- renderLeaflet({                 
  
  #assigning appropriate dataset based on city and year input
  tmp <- get(paste('cendat_',input$cities,"_",input$year, sep = "")) 
  pct_white <- tmp$pct_white #assigning appropriate percent white value 
  
  #assinging appropriate number of white based on year (variable changes based on census year)
  if (input$year == 1990){
  num_white <- tmp$P0070001
} else if (input$year ==2000){
  num_white <- tmp$P003003
}else{
  num_white <-tmp$P003002 # 2010
}
 #set color pallate with range 0-100 for full spectrum 
   pal_all = colorNumeric(palette = input$palette, domain = c(0,100))
 if (input$reverse){
   pal_all = colorNumeric(palette = input$palette, domain = c(0,100), reverse = TRUE)
 }
  
  if(nrow(tmp) >= 1){
    tmp %>% st_transform(crs = "+init=epsg:4326")%>%
    leaflet(height = '100%') %>%  
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addPolygons(popup = ~ str_extract(NAME, "^([^,]*)"), # click on tract for tract name/number 
              stroke = FALSE,
              smoothFactor = 0,
              fillOpacity = 0.5,
              color = ~ pal_all(pct_white),
              label = ~paste0(pct_white, "%, (", num_white, ")")) %>% # hover over tract for % and number
    addLegend("bottomright", 
            pal = pal_all, 
            values = ~ pct_white,
            title = "Census Tract Pct White",
            opacity = 1)
  } else leaflet()
}))

```

Comparing Maps
=====================================
Column {.sidebar}
-----------------------------------------------------------------------

### Comparing White population change over time

```{r}
selectInput("cities_compare", "Choose a city:",
      choices = cities, 
      selected = cities[1])

selectInput("year_left", "Left Map Year:",
      c('1990', '2000', '2010'), 
      selected = '1990')

selectInput("year_right", "Right Map Year:",
      c('1990', '2000', '2010'), 
      selected = '2000')


selectInput("palette2", "Choose a color palette:",
            choices = color_choices, selected = color_choices[1])


```
***
Does this work? 

Column
-------------------------------------

### 

```{r}
(map2<- renderLeaflet({                 
  
    tmp_left <- get(paste('cendat_',input$cities_compare,"_",input$year_left, sep = ""))
    pct_white_left <- tmp_left$pct_white   
    pal_all = colorNumeric(palette = input$palette2, domain = c(0,100))
  
  if (input$year_left == 1990){
    num_white_left  <- tmp_left$P0070001
} else if (input$year_left ==2000){
    num_white_left <- tmp_left$P003003
} else{
    num_white_left <-tmp_left$P003002 # 2010 
}
  
  if(nrow(tmp_left) >= 1){
    tmp_left %>% st_transform(crs = "+init=epsg:4326")%>%
    leaflet() %>%  
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addPolygons(popup = ~ str_extract(NAME, "^([^,]*)"),
              stroke = FALSE,
              smoothFactor = 0,
              fillOpacity = 0.5,
              color = ~ pal_all(pct_white_left),
              label = ~paste0(pct_white_left, "%, (", num_white_left, ")"))
  } else leaflet()
}))

```

Column
-------------------------------------
   
### 

```{r}

(map3<- renderLeaflet({                 

    tmp_right <- get(paste('cendat_',input$cities_compare,"_",input$year_right, sep = ""))
    pct_white_right <- tmp_right$pct_white   
    pal_all2 = colorNumeric(palette = input$palette2, domain = c(0,100))

  if (input$year_right == 1990){
    num_white_right  <- tmp_right$P0070001
} else if (input$year_right ==2000){
    num_white_right <- tmp_right$P003003
} else{
    num_white_right <-tmp_right$P003002 # 2010 
}
 
  if(nrow(tmp_right) >= 1){
    tmp_right %>% st_transform(crs = "+init=epsg:4326")%>%
    leaflet() %>%  
    addProviderTiles(provider = "CartoDB.Positron") %>%
    addPolygons(popup = ~ str_extract(NAME, "^([^,]*)"),
              stroke = FALSE,
              smoothFactor = 0,
              fillOpacity = 0.5,
              color = ~ pal_all2(pct_white_right),
              label = ~paste0(pct_white_right, "%, (", num_white_right, ")")) %>%
    addLegend("bottomright", 
            pal = pal_all2, 
            values = c(0,100),
            title = "Census Tract Pct White",
            opacity = 1)
  } else leaflet()
}))
```   

Permutation Test
=====================================
Column {.tabset .tabset-fade}
-------------------------------------
   
### Figure X
Put plot here
```{r}
```   
 
### Figure Y 
   Put Plot here (Y)
```{r}
```

### Figure Z 
   Put Plot here (Z)
```{r}
```

Column 
-------------------------------------
    
### Analysis
We decided to permute the years for the city of Boston to test the null hypothesis without making any assumptions about the distribution. The permutation test is important because it does not rely on assumptions such as normality by resampling the data many times in order to find a p-value for the permutation distribution. Thus, three permutation tests were performed for the following:

 1. Permuting 1990 & 2000
 2. Permuting 2000 & 2010
 3. Permuting 1990 & 2010

If the null hypothesis is true, there changing the sampling of the year should have **no effect** on the outcome, percentage of white people in the census tracts. 					

For the permutation test, we decided to create 10000 permutations of the assigned conditions. Then, for each of these events, we took the mean difference between the two years for that assignment. Next, we compared the distribution of mean differences we found through the permutation sampling to the observed mean difference. Figure X shows the distribution of mean differences from the permutation test and the vertical line is the observed mean difference in affect score between the years 1990 and 2000. Figure Y is the distribution of permuted mean differences between the years 2000 & 2010. Figure Z is the distribution of permuted mean differences between the years 1990 and 2010. For all three of the permutation tests, we can see that **we can successfully reject the null hypothesis** that there are no observed differences across the years for the percentage of white people in the city of Boston. However, we can see that over time, the observed mean difference is increasingly further away from the permuted distribution of mean differences, which can be seen in Figure Z. This confirms our hypothesis that over time, there have been changes in the percentage of white people in Boston. 
```{r}
```

The approximated **p-value** based on the permutation test was 

Project Explanation
=====================================
What happens here 

R Script
=====================================
This is the code we used to gather and prep the data, as well as perform the permutation tests and save the relevant datasets and objects

Column { vertical_layout: scroll}
-------------------------------------
```{r, eval=F, echo=T}

#### last update ####
# Rachel 5/7 12:30 PM

#### set up ####
rm(list = ls())
setwd('c:/users/juggl_000/Desktop/R Scripts') # set directory 

library(magrittr)
library(texreg)
library(dplyr)
library(tidycensus)
library(ggplot2)
library(ggmap)
library(stringr)
library(tidyverse)
library(leaflet)
library(htmltools)
library(tigris)
library(acs)
library(gridExtra)
library(sf)


#### prep for all maps ####
vars1990 <- c('P0070001') #all white
vars2000 <- c('P003003') #all white
vars2010 <- c('P003002') #all white
pal_all = colorNumeric(palette = "viridis", domain = c(0, 100))
tag.map.title <- tags$style(HTML("
                                 .leaflet-control.map-title { 
                                 transform: translate(-50%,20%);
                                 position: fixed !important;
                                 left: 50%;
                                 text-align: center;
                                 padding-left: 10px; 
                                 padding-right: 10px; 
                                 background: rgba(255,255,255,0.75);
                                 font-weight: bold;
                                 font-size: 28px;
                                 }
                                 "))

title1990 <- tags$div(
  tag.map.title, HTML("Racial Diversity: 1990 Census")) 
title2000 <- tags$div(
  tag.map.title, HTML("Racial Diversity: 2000 Census")) 
title2010 <- tags$div(
  tag.map.title, HTML("Racial Diversity: 2010 Census")) 
```
